### ISSUE TITLE
[not that important] Shift+T (Inspector shortcut key) is available before running

### ISSUE THREAD

**Issue by Phil-Venter** [ajthinking/data-story#9]
`Shift + T` the shortcut for the inspector is available before running the story.
Pressing this displays a blank page which you can only fix by reloading the page (losing, all the stuff and things).

Steps to replicate:
- open Data Story
- add some nodes
- press `Shift + T`

**Comment by ajthinking** [comment]
Hey Phil, nice catch :sweat_smile: Bug fix released: https://github.com/ajthinking/data-story/releases/tag/v0.0.12
Thanks!
